Name: Config
Type: FolderType
Children:
- File: PE_Bar/PE_Bar.yaml
- File: IP/IP.yaml
- Name: SafetyCLX
  Type: BaseDataVariableType
  DataType: Boolean
  Children:
  - Name: ExpressionEvaluator1
    Type: ExpressionEvaluator
    Children:
    - Name: Expression
      Type: BaseDataVariableType
      DataType: String
      ReferenceType: HasParameter
      Value: "{0}&&{1}&&{2}&&{3}"
    - Name: ns=16;Source0
      Type: BaseDataVariableType
      DataType: BaseDataType
      ReferenceType: HasSource
      Children:
      - Name: DynamicLink
        Type: DynamicLink
        DataType: NodePath
        Value: "../../../../../../CommDrivers/RAEtherNet_IPDriver/CLX1/Tags/Controller Tags/Cfg_Safety_CLX"
    - Name: ns=16;Source1
      Type: BaseDataVariableType
      DataType: BaseDataType
      ReferenceType: HasSource
      Children:
      - Name: DynamicLink
        Type: DynamicLink
        DataType: NodePath
        Value: "../../../../../../CommDrivers/RAEtherNet_IPDriver/CLX2/Tags/Controller Tags/Cfg_Safety_CLX"
    - Name: ns=16;Source2
      Type: BaseDataVariableType
      DataType: BaseDataType
      ReferenceType: HasSource
      Children:
      - Name: DynamicLink
        Type: DynamicLink
        DataType: NodePath
        Value: "../../../../../../CommDrivers/RAEtherNet_IPDriver/CLX3/Tags/Controller Tags/Cfg_Safety_CLX"
    - Name: ns=16;Source3
      Type: BaseDataVariableType
      DataType: BaseDataType
      ReferenceType: HasSource
      Children:
      - Name: DynamicLink
        Type: DynamicLink
        DataType: NodePath
        Value: "../../../../../../CommDrivers/RAEtherNet_IPDriver/CLX4/Tags/Controller Tags/Cfg_Safety_CLX"
- Name: LanguageId
  Type: BaseDataVariableType
  DataType: Int32
  Value: 1
- Name: LogFalse
  Type: BaseDataVariableType
  DataType: Boolean
- Name: LogTrue
  Type: BaseDataVariableType
  DataType: Boolean
  Value: true
